dotnet-sample/WebApp1/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApp1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

dotnet-sample/WebApp1/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Common.BLL;
using Common;
using ServiceStack.Text;
using System.Text;

namespace WebApp1.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IFileProcessor _fileProcessor;
        private readonly ITableStorageService _tableStorageService;

        public IndexModel(ILogger<IndexModel> logger,
            IFileProcessor fileProcessor,
            ITableStorageService tableStorageService)
        {
            _logger = logger;
            _fileProcessor = fileProcessor;
            _tableStorageService = tableStorageService;
        }

        public IFormFile FormFile { get; set; }

        public bool ReportOnly { get; set; }

        public List<Common.Entities.FileInfo> UploadedFiles { get; set; }

        public async Task<ActionResult> OnGet()
        {
            UploadedFiles = _tableStorageService.GetAllFileInfo().ToList();

            return Page();
        }

        public ActionResult OnPost()
        {
            if (this.ModelState.IsValid)
            {
                _fileProcessor.Start(FormFile, ReportOnly);
                return RedirectToPage("/index");
            }

            UploadedFiles = _tableStorageService.GetAllFileInfo().ToList();

            return Page();
        }

        public IActionResult OnGetDownloadCsv(string fileName, Guid fileId)
        {
            try
            {

                var successes = _tableStorageService.GetAllSuccessForFile(fileId);

                var serializedString = CsvSerializer.SerializeToString(successes);
                var stream = new MemoryStream(Encoding.UTF8.GetBytes(serializedString));
                FileStreamResult result = new FileStreamResult(stream, "text/csv")
                {
                    FileDownloadName = $"Download-Report.csv"
                };
                _logger.LogInformation(EventCodes.WebApp1.UI.Trace.UI_WEBAPP1_CSV_DOWNLOAD, "filename: {fileName} downloaded by user: {user}", fileName, User.Identity?.Name);

                return result;
            }
            catch (Exception ex)
            {
                _logger.LogInformation(EventCodes.WebApp1.UI.Errors.UI_WEBAPP1_FAILURE_DOWNLOADING_FILE, "user: {user} encountered an error downloading {filename}. Error message: {errorMessage}", User.Identity?.Name, fileName, ex.Message);
                return Page();
            }
        }
    }
}

dotnet-sample/WebApp1/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp1.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

dotnet-sample/WebApp1/Pages/User.cshtml.cs
using Ardalis.GuardClauses;
using Azure.Messaging.ServiceBus;
using Common;
using Common.Entities;
using Common.ServiceBus;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Azure;
using System.Net;
using WebApp1.BLL;

namespace WebApp1.Pages
{
    public class UserModel : PageModel
    {

        [BindProperty]
        public string UserName { get; set; }

        public bool? UserFound { get; set; }
        public string CreatedDateTime { get; set; }
        public string LastLogInDateTime { get; set; }
        public string LastPasswordChangeDateTime { get; set; }
        public string AccountEnabled { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ObjectId { get; set; }

        private readonly IUserService _userService;
        private readonly ILogger<UserModel> _logger;
        private readonly ServiceBusClient _serviceBusClient;
        private ServiceBusSender _serviceBusSender;


        public UserModel(IUserService userService,
            ILogger<UserModel> logger,
            ServiceBusConfig serviceBusConfig,
            IAzureClientFactory<ServiceBusClient> serviceBusClientFactory)
        {
            _userService = userService;
            _logger = logger;
            _serviceBusClient = serviceBusClientFactory.CreateClient(Constants.ServiceBusIdentifier);
        }

        public void OnGet()
        {
            Page();
        }

        public async Task<IActionResult> OnPost(string username)
        {
            var model = await _userService.GetUserModel(username.ToLower());
            _logger.LogInformation(EventCodes.WebApp1.UI.Trace.UI_WEBAPP1_USER_TOOL_USER_SEARCHED, "user: {user} searched for username: {username}", User.Identity?.Name, username);
            if (model.UserFound)
            {
                UserFound = true;
                ObjectId = model.ObjectId;
                CreatedDateTime = model.Created;
                LastLogInDateTime = model.LastLogIn;
                AccountEnabled = model.AccountEnabled;
                FirstName = model.FirstName;
                LastName = model.LastName;
            }
            else
            {
                UserFound = false;
            }

            return Page();
        }

        public async Task<IActionResult> OnGetMarkDisabled(string objectId)
        {
            var result = new HttpResponseMessage();

            Guard.Against.NullOrEmpty(objectId, nameof(objectId), $"Username must be provided");

            var request = new UpdateUserRequest()
            {
                CorrelationId = Guid.NewGuid().ToString(),
                AccountEnabled = false
            };

            try
            {

                var response = await _userService.Patch(Guid.Parse(objectId), request, HttpContext);
                _logger.LogInformation(EventCodes.WebApp1.UI.Trace.UI_WEBAPP1_USER_TOOL_ACCOUNT_MARKED_AS_DISABLED, "user by objectId : {objectId} marked as disabled", objectId);

                //result.Content = new StringContent(JsonConvert.SerializeObject(response));

                return new OkResult();
            }
            catch (HttpRequestException httpEx)
            {
                _logger.LogInformation(EventCodes.WebApp1.UI.Errors.UI_WEBAPP1_USER_TOOL_ACCOUNT_MARKED_AS_DISABLED_FAILED, "Failed to disable user. Request: {request}. Error: {error} StatusCode: {statusCode}", request.ToJson(), httpEx.Message, httpEx.StatusCode);

                return HandleMarkingResponse(httpEx.StatusCode.Value);

            }
            catch (Exception ex)
            {
                _logger.LogInformation(EventCodes.WebApp1.UI.Errors.UI_WEBAPP1_USER_TOOL_ACCOUNT_MARKED_AS_DISABLED_FAILED, "Failed to disable user. Request: {request}. Error: {error}", request.ToJson(), ex.Message);

                return HandleMarkingResponse(HttpStatusCode.BadRequest);
            }
        }

        private IActionResult HandleMarkingResponse(HttpStatusCode statusCode)
        {
            var httpResponse = new ObjectResult(new { message = "http request exception" });
            httpResponse.StatusCode = (int)statusCode;
            httpResponse.ContentTypes.Add("application/json");// Set the Content-Type header to application/json

            if (statusCode == HttpStatusCode.Unauthorized)
            {
                httpResponse.StatusCode = (int)HttpStatusCode.Unauthorized;
                httpResponse.Value = HttpStatusCode.Unauthorized.ToString();
                return httpResponse;
            }

            if (statusCode == HttpStatusCode.Forbidden)
            {
                httpResponse.StatusCode = (int)HttpStatusCode.Forbidden;
                httpResponse.Value = HttpStatusCode.Forbidden.ToString();

                return httpResponse;

            }

            return httpResponse;

        }
    }
}

dotnet-sample/WebApp1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Upload";
}

<div class="card mb-4">
    <div class="card-header">
        Upload
    </div>
    <div class="card-body">          
        <form class="form-inline" method="post" enctype="multipart/form-data">
    
            <div class="col-sm-10 row">
                <div class="row">

                    <div class="form-group col-lg-6">
                        <input type="file" asp-for="FormFile" class="form-control mb-2 mr-sm-2" required />
                        <span style="color: red;" asp-validation-for="FormFile"></span>
                    </div>

                    <div class="form-group col-lg-2">
                        <input class="form-check-input" asp-for="ReportOnly" /> Report Only
                    </div>

                    <div class="form-group col-lg-2 text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>

                </div>
            </div>  

        </form>


    </div>

</div>

<div class="alert alert-warning" role="alert">
  Partial reports can be downloaded before processing has completed - for the full report, please leave 2 minutes per 100 items before downloading.
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">File Name</th>
      <th scope="col">Upload Date/Time</th>
      <th scope="col">Record Count</th>
      <th scope="col">Report Only</th>
      <th scope="col">Status</th>
      <th scope="col">Completed At</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    @foreach(var row in Model.UploadedFiles)
    {
        <tr>
            <td>@row.Name</td>
            <td>@row.UploadAt.ToString("dd/MM/yyyy hh:mm:ss tt zzz")</td>
            <td>@row.RecordCount</td>
            <td>@row.ReportOnly</td>
            <td>@row.Status</td>
            <td>@((row.CompletedAt == DateTimeOffset.MinValue) ? "-" : @row.CompletedAt.ToString("dd/MM/yyyy hh:mm:ss tt zzz"))</td>
            <td><a asp-page-handler="DownloadCsv" asp-route-fileName="@row.Name" asp-route-fileId="@row.Id">Download Report</a></td>
        </tr>        
    }
  </tbody>
</table>

dotnet-sample/WebApp1/Pages/User.cshtml
@page
@model UserModel
@{
    ViewData["Title"] = "User Tool";
}

<div class="card mb-4">
    <div class="card-header">
        User Search
    </div>
    <div class="card-body">
        <form class="form-inline" method="post">

            <div class="col-sm-10 row">
                <div class="row">

                    <div class="form-group col-lg-6">
                        <input asp-for="UserName" class="form-control mb-2 mr-sm-2" required>
                        <span asp-validation-for="UserName"></span>
                    </div>

                    <div class="form-group col-lg-2 text-right">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>

                </div>
            </div>

        </form>
    </div>
</div>


<div id="disabledSuccess" class="position-relative alert alert-success alert-dismissible" style="display:none" role="alert">
    Account has been marked as disabled!
    <button type="button" class="close position-absolute" data-bs-dismiss="alert" aria-label="Close" style="right:10px">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div id="disabledFailure" class="position-relative alert alert-warning alert-dismissible" style="display:none" role="alert">
    Failed to mark as disabled.
    <button type="button" class="close position-absolute" data-bs-dismiss="alert" aria-label="Close" style="right:10px">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


@if (Model.UserFound == true)
{
    <div class="card mb-4">
        <div class="card-header">
            User - @Model.UserName
        </div>
        <div class="card-body">
            <dl>
                <dt>Created</dt>
                <dd>@Model.CreatedDateTime</dd>
                <dt>Last Sign In</dt>
                <dd>@Model.LastLogInDateTime</dd>
                <dt>Account Enabled</dt>
                <dd id="accountEnabled">@Model.AccountEnabled</dd>
                <dt>First Name</dt>
                <dd id="identityStatus">@Model.FirstName</dd>
                <dt>Last Name</dt>
                <dd id="lastIdentityStatusChange">@Model.LastName</dd>
            </dl>
        </div>
        <div class="card-footer">
            <button class="btn btn-secondary d-inline-block" type="button" id="markDisabled" onclick="markDisabled('@Model.ObjectId')" @((Model.AccountEnabled == "False") ? "disabled" : "")>Mark Disabled</button>
        </div>
    </div>
}
@if (Model.UserFound == false)
{
    <div class="alert alert-primary">No user found - enter another username</div>
}